name: ServerManager
version: 1.3
author: Nosmoze
main: fr.servermanager.main.ServerManager
api-version: 1.13
commands:
  manager:
    description: Main command
  cancel:
    description: Cancel instructions